#!/usr/bin/env node
/**
 * Builds the portable single-executable distribution.
 *
 * Node 22 single-executable applications only accept a CommonJS entry, so the
 * ESM source tree is bundled with esbuild first, then the blob is injected into
 * a copy of node.exe with postject.
 *
 * Verification is deliberately falsifiable:
 *   1. the preparation blob must contain the injection marker, proving the
 *      renderer script really was embedded as a SEA asset;
 *   2. the produced executable must answer `status`, proving the bundle loads
 *      and the argv dispatch works.
 */
import { execFile } from "node:child_process";
import fs from "node:fs/promises";
import path from "node:path";
import { promisify } from "node:util";

const execFileAsync = promisify(execFile);
const BUILD_SCRIPT_DIR = path.dirname(path.resolve(process.argv[1]));
const PROJECT_ROOT = path.resolve(BUILD_SCRIPT_DIR, "..");

const DIST_DIR = path.join(PROJECT_ROOT, "dist");
const PORTABLE_DIR = path.join(DIST_DIR, "portable");
const BUNDLE_PATH = path.join(DIST_DIR, "bundle.cjs");
const SEA_CONFIG_PATH = path.join(DIST_DIR, "sea-config.json");
const BLOB_PATH = path.join(DIST_DIR, "sea-prep.blob");
const EXE_NAME = "TraeEnhancer.exe";
const EXE_PATH = path.join(DIST_DIR, EXE_NAME);
const PORTABLE_EXE_PATH = path.join(PORTABLE_DIR, EXE_NAME);
const ENTRIES = {
  entryPoint: path.join(PROJECT_ROOT, "src", "sea-entry.js"),
  injectSource: path.join(PROJECT_ROOT, "src", "ui", "inject.js"),
  postjectCli: path.join(PROJECT_ROOT, "node_modules", "postject", "dist", "cli.js"),
  trayScript: path.join(PROJECT_ROOT, "scripts", "tray.ps1"),
  cmdEntry: path.join(PROJECT_ROOT, "scripts", "trae-enhancer.cmd"),
  readme: path.join(PROJECT_ROOT, "README.md"),
};

/**
 * The blob stores bundled assets verbatim, so a marker from the renderer script
 * proves the asset was embedded.
 */
const INJECT_MARKER = "__API_BASE__";
const SENTINEL_FUSE = "NODE_SEA_FUSE_fce680ab2cc467b6e072b8b5df1996b2";

function log(message) {
  console.log(`[build] ${message}`);
}

async function assertExists(filePath, label) {
  try {
    await fs.access(filePath);
  } catch {
    throw new Error(`${label} is missing: ${filePath}`);
  }
}

async function assertAsciiFile(filePath, label) {
  const bytes = await fs.readFile(filePath);
  if (bytes.subarray(0, 3).equals(Buffer.from([0xef, 0xbb, 0xbf]))) {
    throw new Error(`${label} must not contain a BOM: ${filePath}`);
  }
  const nonAscii = bytes.findIndex((byte) => byte > 0x7f);
  if (nonAscii >= 0) {
    throw new Error(`${label} must stay pure ASCII; found byte 0x${bytes[nonAscii].toString(16)} at offset ${nonAscii}`);
  }
}

async function bundleEntry() {
  let esbuild;
  try {
    esbuild = await import("esbuild");
  } catch {
    throw new Error(
      "esbuild is not installed. Run `npm install` before building the executable.",
    );
  }
  const result = await esbuild.build({
    entryPoints: [ENTRIES.entryPoint],
    outfile: BUNDLE_PATH,
    bundle: true,
    platform: "node",
    format: "cjs",
    target: "node22",
    charset: "utf8",
    logLevel: "warning",
    logOverride: { "empty-import-meta": "silent" },
    define: { __APP_BUNDLE_ROOT__: "__dirname" },
    banner: {
      js: "// Generated by scripts/build-exe.js. Do not edit.",
    },
  });
  if (result.warnings.length) {
    for (const warning of result.warnings) log(`esbuild warning: ${warning.text}`);
  }
  const stat = await fs.stat(BUNDLE_PATH);
  log(`bundled ${path.relative(PROJECT_ROOT, BUNDLE_PATH)} (${stat.size} bytes)`);
}

async function writeSeaConfig() {
  const config = {
    main: BUNDLE_PATH,
    output: BLOB_PATH,
    disableExperimentalSEAWarning: true,
    assets: {
      "inject.js": ENTRIES.injectSource,
    },
  };
  await fs.writeFile(SEA_CONFIG_PATH, `${JSON.stringify(config, null, 2)}\n`, "utf8");
  log(`wrote ${path.relative(PROJECT_ROOT, SEA_CONFIG_PATH)}`);
}

async function generateBlob() {
  const { stdout, stderr } = await execFileAsync(
    process.execPath,
    ["--experimental-sea-config", SEA_CONFIG_PATH],
    { cwd: PROJECT_ROOT, encoding: "utf8", windowsHide: true },
  );
  if (stdout.trim()) log(stdout.trim());
  if (stderr.trim()) log(stderr.trim());
}

async function verifyBlobEmbedsAssets() {
  const blob = await fs.readFile(BLOB_PATH);
  const marker = Buffer.from(INJECT_MARKER, "utf8");
  if (!blob.includes(marker)) {
    throw new Error(
      `the preparation blob does not contain ${INJECT_MARKER}; the renderer script was not embedded`,
    );
  }
  log(`blob embeds the renderer script (found ${INJECT_MARKER})`);
}

async function injectBlob() {
  await assertExists(ENTRIES.postjectCli, "the postject CLI");
  await fs.copyFile(process.execPath, EXE_PATH);
  const { stdout } = await execFileAsync(
    process.execPath,
    [
      ENTRIES.postjectCli,
      EXE_PATH,
      "NODE_SEA_BLOB",
      BLOB_PATH,
      "--sentinel-fuse",
      SENTINEL_FUSE,
    ],
    { cwd: PROJECT_ROOT, encoding: "utf8", windowsHide: true, maxBuffer: 8 * 1024 * 1024 },
  );
  if (stdout.trim()) log(stdout.trim());
  const stat = await fs.stat(EXE_PATH);
  const nodeStat = await fs.stat(process.execPath);
  if (stat.size <= nodeStat.size) {
    throw new Error("the built executable is not larger than node.exe; injection failed");
  }
  log(`built ${path.relative(PROJECT_ROOT, EXE_PATH)} (${(stat.size / 1048576).toFixed(1)} MB)`);
}

async function verifyExecutableRuns() {
  const { stdout } = await execFileAsync(EXE_PATH, ["status"], {
    cwd: DIST_DIR,
    encoding: "utf8",
    windowsHide: true,
    timeout: 60000,
  });
  if (!/daemon\s*:/.test(stdout)) {
    throw new Error(`the executable did not answer status as expected:\n${stdout}`);
  }
  log("the executable answers `status`");
  log(stdout.trim().split(/\r?\n/).join("\n        "));
}

async function cleanupVerificationState() {
  await fs.rm(path.join(DIST_DIR, "logs"), { recursive: true, force: true });
}

async function assemblePortableFolder() {
  await fs.mkdir(path.join(PORTABLE_DIR, "scripts"), { recursive: true });
  await fs.rm(path.join(PORTABLE_DIR, "logs"), { recursive: true, force: true });
  await fs.copyFile(EXE_PATH, PORTABLE_EXE_PATH);
  await fs.copyFile(ENTRIES.trayScript, path.join(PORTABLE_DIR, "scripts", "tray.ps1"));
  await fs.copyFile(ENTRIES.cmdEntry, path.join(PORTABLE_DIR, "scripts", "trae-enhancer.cmd"));
  await fs.copyFile(ENTRIES.readme, path.join(PORTABLE_DIR, "README.md"));
  for (const relative of [
    EXE_NAME,
    "README.md",
    path.join("scripts", "trae-enhancer.cmd"),
    path.join("scripts", "tray.ps1"),
  ]) {
    await assertExists(path.join(PORTABLE_DIR, relative), `portable ${relative}`);
  }
  log(`assembled ${path.relative(PROJECT_ROOT, PORTABLE_DIR)}`);
}

async function main() {
  await fs.mkdir(DIST_DIR, { recursive: true });
  log(`node ${process.version} at ${process.execPath}`);
  await assertAsciiFile(ENTRIES.trayScript, "tray script");
  await assertAsciiFile(ENTRIES.cmdEntry, "cmd entry");
  await bundleEntry();
  await writeSeaConfig();
  await generateBlob();
  await verifyBlobEmbedsAssets();
  await injectBlob();
  await verifyExecutableRuns();
  await cleanupVerificationState();
  await assemblePortableFolder();
  log("done");
  log(`portable build: ${PORTABLE_EXE_PATH}`);
}

main().catch((error) => {
  console.error(`[build] failed: ${error instanceof Error ? error.message : error}`);
  process.exitCode = 1;
});
